spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: Authorization, Content-Type
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${EUREKA_USER:god}:${EUREKA_PASS:ZeroTwoBestWaifu}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

server:
  port: 8080
