spring:
  main:
    allow-circular-references: true
  application:
    name: product-service
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql=false:
    hibernate:
      ddl-auto: update
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASS:896699}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    driver-class-name: org.postgresql.Driver

  cloud:
    consul:
      host: ${CONSUL_URL:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${EUREKA_USER:god}:${EUREKA_PASS:ZeroTwoBestWaifu}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
server:
  port: ${PORT:8082}
